### ISSUE TITLE
configs/sr-8040-debian-buster.inc wants to use a file in /home/josua

### ISSUE THREAD

**Issue by skrueger8** [mxOBS/imagebuilder#1]
I have a slight feeling this won't work anywhere (well except for Josua) :)

https://github.com/mxOBS/imagebuilder/blob/master/configs/sr-8040-debian-buster.inc#L53

```
install -v -m644 -o root -g root /home/josua/Downloads/armada-8040-clearfog-gt-8k.dtb "$buildroot/etc/flash-kernel/dtbs/"
````

**Comment by Josua-SR** [comment]
good point!
The DTB is now included in the bsp-solidrun-8040 deb, and I removed the local blobs from the recipe.

**Comment by skrueger8** [comment]
Seems to be fixed with https://github.com/mxOBS/imagebuilder/commit/0596e55dd4d85dacda1191ff9f15ca5be0f674e4

Thanks!
